#!/usr/bin/env python3
import os, time, json, base64
os.environ['TZ'] = 'Asia/Ho_Chi_Minh'
time.tzset()

SHEET_ID        = os.environ.get('SHEET_ID', '')
SHEET_NAME      = os.environ.get('SHEET_NAME', 'Sheet1')
INSTAGRAM_URL   = 'https://www.instagram.com'
CREDENTIALS_FILE = '/tmp/credentials.json'
SESSION_FILE     = '/tmp/instagram_session.json'

import subprocess, sys, random
from datetime import datetime, timedelta

print(f"⏰ Múi giờ: {time.strftime('%Z %z')}")
print(f"🕐 Giờ hiện tại: {datetime.now().strftime('%d/%m/%Y %H:%M:%S')}")

def restore_secrets():
    creds_b64 = os.environ.get('CREDENTIALS_JSON_B64', '')
    if not creds_b64:
        print('❌ Thiếu secret CREDENTIALS_JSON_B64')
        sys.exit(1)
    with open(CREDENTIALS_FILE, 'wb') as f:
        f.write(base64.b64decode(creds_b64))
    print(f'✅ Khôi phục credentials.json → {CREDENTIALS_FILE}')

    session_b64 = os.environ.get('INSTAGRAM_SESSION_B64', '')
    if not session_b64:
        print('❌ Thiếu secret INSTAGRAM_SESSION_B64')
        sys.exit(1)
    with open(SESSION_FILE, 'wb') as f:
        f.write(base64.b64decode(session_b64))
    print(f'✅ Khôi phục instagram_session.json → {SESSION_FILE}')

def connect_sheet():
    import gspread
    from google.oauth2.service_account import Credentials
    scopes = [
        'https://www.googleapis.com/auth/spreadsheets',
        'https://www.googleapis.com/auth/drive'
    ]
    creds = Credentials.from_service_account_file(CREDENTIALS_FILE, scopes=scopes)
    client = gspread.authorize(creds)
    return client.open_by_key(SHEET_ID).worksheet(SHEET_NAME)

def get_pending_posts(sheet):
    records = sheet.get_all_records(
        expected_headers=['content', 'image_url', 'hashtags', 'scheduled_time', 'status']
    )
    now = datetime.now()
    result = []
    for i, row in enumerate(records, start=2):
        status = str(row.get('status', '')).strip().lower()
        if status != 'pending':
            continue
        content = str(row.get('content', '')).strip()
        image_url = str(row.get('image_url', '')).strip()
        # Instagram bắt buộc phải có ảnh để đăng post ảnh
        if not image_url:
            print(f'⚠️ Row {i}: Không có image_url, bỏ qua (Instagram cần ảnh)')
            continue
        scheduled = str(row.get('scheduled_time', '')).strip()
        should_post = False
        if not scheduled:
            should_post = True
        else:
            try:
                scheduled_dt = datetime.strptime(scheduled, '%d/%m/%Y %H:%M')
                if now >= scheduled_dt - timedelta(minutes=5):
                    should_post = True
            except ValueError:
                print(f'⚠️ Row {i}: Sai định dạng thời gian: {scheduled}')
        if should_post:
            result.append({
                'row': i,
                'content': content,
                'image_url': image_url,
                'hashtags': str(row.get('hashtags', '')).strip(),
                'scheduled_time': scheduled
            })
    return result

def update_status(sheet, row_num, status, post_id=''):
    sheet.update_cell(row_num, 5, status)
    if post_id:
        sheet.update_cell(row_num, 6, post_id)
    sheet.update_cell(row_num, 7, datetime.now().strftime('%Y-%m-%d %H:%M:%S'))
    print(f'   📝 Cập nhật row {row_num}: {status}')

def _write_pw_worker():
    path = '/tmp/pw_worker.py'
    lines = [
        'import sys, json, random, time, os, re\n',
        'import urllib.request\n',
        'from playwright.sync_api import sync_playwright\n',
        '\n',
        'args          = json.loads(os.environ["PW_PAYLOAD"])\n',
        'content       = args["content"]\n',
        'image_url     = args.get("image_url", "")\n',
        'hashtags      = args.get("hashtags", "").strip()\n',
        'SESSION_FILE  = args["session_file"]\n',
        'INSTAGRAM_URL = args["instagram_url"]\n',
        '\n',
        'def log(msg): print(msg, flush=True)\n',
        '\n',
        'def get_direct_image_url(url):\n',
        '    if not url: return ""\n',
        '    m = re.search(r"/file/d/([^/]+)", url)\n',
        '    if m: return f"https://drive.google.com/uc?export=download&id={m.group(1)}"\n',
        '    m = re.search(r"[?&]id=([^&]+)", url)\n',
        '    if m: return f"https://drive.google.com/uc?export=download&id={m.group(1)}"\n',
        '    return url\n',
        '\n',
        'def download_image(url):\n',
        '    if not url: return None\n',
        '    try:\n',
        '        direct = get_direct_image_url(url)\n',
        '        log(f"   🖼️ Tải ảnh: {direct[:80]}")\n',
        '        dest = "/tmp/post_image.jpg"\n',
        '        req = urllib.request.Request(direct, headers={"User-Agent": "Mozilla/5.0"})\n',
        '        with urllib.request.urlopen(req, timeout=30) as resp:\n',
        '            with open(dest, "wb") as f:\n',
        '                f.write(resp.read())\n',
        '        size = os.path.getsize(dest)\n',
        '        log(f"   ✅ Tải ảnh xong ({size} bytes)")\n',
        '        return dest if size > 1000 else None\n',
        '    except Exception as e:\n',
        '        log(f"   ⚠️ Không tải được ảnh: {e}")\n',
        '        return None\n',
        '\n',
        'def dismiss_popups(page):\n',
        '    popup_sels = [\n',
        '        \'button:has-text("Allow")\',\n',
        '        \'button:has-text("Accept all")\',\n',
        '        \'button:has-text("Only allow essential cookies")\',\n',
        '        \'button:has-text("Not Now")\',\n',
        '        \'button:has-text("Không bây giờ")\',\n',
        '        \'button:has-text("Turn On Notifications")\',\n',
        '        \'button:has-text("Later")\',\n',
        '        \'button:has-text("Close")\',\n',
        '        \'[aria-label="Close"]\',\n',
        '    ]\n',
        '    for sel in popup_sels:\n',
        '        try:\n',
        '            btn = page.locator(sel).first\n',
        '            if btn.is_visible():\n',
        '                btn.click()\n',
        '                log(f"   🚫 Đóng popup: {sel}")\n',
        '                time.sleep(0.5)\n',
        '        except:\n',
        '            pass\n',
        '\n',
        'if not image_url:\n',
        '    log("ERR:NO_IMAGE")\n',
        '    sys.exit(6)\n',
        '\n',
        'if not os.path.exists(SESSION_FILE):\n',
        '    log("ERR:NO_SESSION")\n',
        '    sys.exit(1)\n',
        '\n',
        'local_image = download_image(image_url)\n',
        'if not local_image:\n',
        '    log("ERR:IMAGE_DOWNLOAD_FAILED")\n',
        '    sys.exit(6)\n',
        '\n',
        'INIT_SCRIPT = (\n',
        '    "Object.defineProperty(navigator, \\"webdriver\\", {get: () => undefined});"\n',
        '    " window.chrome = {runtime: {}, loadTimes: function(){}, csi: function(){}, app: {}};"\n',
        '    " Object.defineProperty(navigator, \\"plugins\\", {get: () => [1,2,3,4,5]});"\n',
        '    " Object.defineProperty(navigator, \\"languages\\", {get: () => [\\"vi-VN\\",\\"vi\\",\\"en-US\\",\\"en\\"]});"\n',
        ')\n',
        '\n',
        '# Gộp caption + hashtags\n',
        'caption = content\n',
        'if hashtags:\n',
        '    caption = caption + "\\n\\n" + hashtags\n',
        '\n',
        'with sync_playwright() as p:\n',
        '    browser = p.chromium.launch(\n',
        '        headless=True,\n',
        '        args=["--no-sandbox", "--disable-dev-shm-usage",\n',
        '              "--disable-blink-features=AutomationControlled",\n',
        '              "--window-size=1280,800"]\n',
        '    )\n',
        '    context = browser.new_context(\n',
        '        storage_state=SESSION_FILE,\n',
        '        user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36",\n',
        '        viewport={"width": 1280, "height": 800},\n',
        '        locale="vi-VN",\n',
        '        timezone_id="Asia/Ho_Chi_Minh",\n',
        '    )\n',
        '    context.add_init_script(INIT_SCRIPT)\n',
        '    page = context.new_page()\n',
        '    try:\n',
        '        log("   🌐 Mở Instagram...")\n',
        '        # Dùng domcontentloaded thay networkidle — Instagram chặn networkidle trên cloud IP\n',
        '        for attempt in range(3):\n',
        '            try:\n',
        '                page.goto(INSTAGRAM_URL, wait_until="domcontentloaded", timeout=60000)\n',
        '                break\n',
        '            except Exception as ge:\n',
        '                log(f"   ⚠️ goto attempt {attempt+1}/3 lỗi: {ge}")\n',
        '                if attempt == 2: raise\n',
        '                time.sleep(5)\n',
        '        time.sleep(random.uniform(3.0, 5.0))\n',
        '\n',
        '        log(f"   🔗 URL: {page.url}")\n',
        '        log(f"   📄 Title: {page.title()}")\n',
        '\n',
        '        if "login" in page.url or "accounts/login" in page.url:\n',
        '            page.screenshot(path="/tmp/debug_login.png")\n',
        '            log("ERR:SESSION_EXPIRED")\n',
        '            sys.exit(2)\n',
        '\n',
        '        log("   ✅ Đã đăng nhập Instagram")\n',
        '        dismiss_popups(page)\n',
        '        time.sleep(random.uniform(2.0, 3.0))\n',
        '\n',
        '        # ── DEBUG: Dump elements để biết aria-label thực tế ──\n',
        '        try:\n',
        '            nav_info = page.evaluate("""\n',
        '                () => {\n',
        '                    const els = Array.from(document.querySelectorAll("a,button,[role=\'button\'],svg"));\n',
        '                    return els.filter(e => e.offsetParent !== null).map(e => ({\n',
        '                        tag: e.tagName,\n',
        '                        aria: e.getAttribute("aria-label") || "",\n',
        '                        href: e.getAttribute("href") || "",\n',
        '                        text: (e.innerText || "").trim().slice(0, 30)\n',
        '                    })).filter(e => e.aria || e.href || e.text).slice(0, 50);\n',
        '                }\n',
        '            """)\n',
        '            log("   🔍 [DEBUG] Elements visible:")\n',
        '            for el in nav_info:\n',
        '                log(f\'      {el["tag"]} aria="{el["aria"]}" href="{el["href"]}" text="{el["text"]}"\')\n',
        '        except Exception as e:\n',
        '            log(f"   ⚠️ Không dump được: {e}")\n',
        '\n',
        '        page.screenshot(path="/tmp/debug_home.png")\n',
        '\n',
        '        # ── Bước 1: Click nút tạo bài mới ──\n',
        '        compose_clicked = False\n',
        '        compose_sels = [\n',
        '            \'svg[aria-label="Bài viết mới"]\',\n',
        '            \'[aria-label="Bài viết mới"]\',\n',
        '            \'svg[aria-label="New post"]\',\n',
        '            \'[aria-label="New post"]\',\n',
        '            \'[aria-label="Create"]\',\n',
        '            \'[aria-label="Tạo"]\',\n',
        '            \'svg[aria-label="Create"]\',\n',
        '            \'a[href="/create/select/"]\',\n',
        '            \'a[href*="/create"]\',\n',
        '        ]\n',
        '        for sel in compose_sels:\n',
        '            try:\n',
        '                el = page.locator(sel).first\n',
        '                el.wait_for(state="visible", timeout=3000)\n',
        '                # Nếu là SVG thì click vào thẻ A cha\n',
        '                if sel.startswith("svg"):\n',
        '                    el.locator("xpath=ancestor::a[1]").click()\n',
        '                else:\n',
        '                    el.click()\n',
        '                log(f"   🖱️ Click New Post: {sel}")\n',
        '                compose_clicked = True\n',
        '                break\n',
        '            except:\n',
        '                pass\n',
        '\n',
        '        # Fallback JS: click thẻ A chứa svg[aria-label="Bài viết mới"] hoặc các biến thể\n',
        '        if not compose_clicked:\n',
        '            try:\n',
        '                clicked = page.evaluate("""\n',
        '                    () => {\n',
        '                        const keywords = ["bài viết mới", "new post", "create", "tạo"];\n',
        '                        const svgs = Array.from(document.querySelectorAll("svg[aria-label]"));\n',
        '                        const svg = svgs.find(s => {\n',
        '                            const a = (s.getAttribute("aria-label") || "").toLowerCase();\n',
        '                            return keywords.some(k => a.includes(k));\n',
        '                        });\n',
        '                        if (!svg) return null;\n',
        '                        // Leo lên tìm thẻ A cha gần nhất\n',
        '                        let el = svg;\n',
        '                        for (let i = 0; i < 6; i++) {\n',
        '                            el = el.parentElement;\n',
        '                            if (!el) break;\n',
        '                            if (el.tagName === "A" || el.getAttribute("role") === "button") {\n',
        '                                el.click();\n',
        '                                return svg.getAttribute("aria-label");\n',
        '                            }\n',
        '                        }\n',
        '                        svg.click();\n',
        '                        return "svg-direct-click";\n',
        '                    }\n',
        '                """)\n',
        '                if clicked:\n',
        '                    log(f"   🖱️ JS fallback compose: {clicked}")\n',
        '                    compose_clicked = True\n',
        '            except Exception as e:\n',
        '                log(f"   ⚠️ JS compose lỗi: {e}")\n',
        '\n',
        '        if not compose_clicked:\n',
        '            log("ERR:NO_COMPOSE_BUTTON")\n',
        '            page.screenshot(path="/tmp/debug_no_compose.png")\n',
        '            sys.exit(3)\n',
        '\n',
        '        time.sleep(random.uniform(1.5, 2.5))\n',
        '\n',
        '        # ── Bước 1b: Click "Bài viết" trong submenu (nếu có) ──\n',
        '        # Sau khi click nút Tạo (+), Instagram hiện submenu: Bài viết / Reels / v.v.\n',
        '        # Phải click "Bài viết" mới ra màn upload ảnh\n',
        '        submenu_clicked = False\n',
        '        try:\n',
        '            submenu_clicked_val = page.evaluate("""\n',
        '                () => {\n',
        '                    const keywords = ["bài viết", "post", "photo", "ảnh"];\n',
        '                    const btns = Array.from(document.querySelectorAll("button,[role=\'button\'],a,span,div"));\n',
        '                    // Tìm item "Bài viết" trong submenu — KHÔNG phải "Bài viết mới"\n',
        '                    const t = btns.find(b => {\n',
        '                        if (b.offsetParent === null) return false;\n',
        '                        const txt = (b.innerText || b.textContent || "").trim().toLowerCase();\n',
        '                        const aria = (b.getAttribute("aria-label") || "").trim().toLowerCase();\n',
        '                        // Chính xác "bài viết" hoặc "post" (không chứa "mới"/"new")\n',
        '                        return (txt === "bài viết" || txt === "post" || aria === "bài viết" || aria === "post");\n',
        '                    });\n',
        '                    if (t) { t.click(); return t.innerText || t.getAttribute("aria-label") || "clicked"; }\n',
        '                    return null;\n',
        '                }\n',
        '            """)\n',
        '            if submenu_clicked_val:\n',
        '                log(f"   🖱️ Click submenu Bài viết: {submenu_clicked_val}")\n',
        '                submenu_clicked = True\n',
        '                time.sleep(random.uniform(1.5, 2.5))\n',
        '            else:\n',
        '                log("   ℹ️ Không thấy submenu Bài viết — có thể đã mở thẳng dialog upload")\n',
        '        except Exception as e:\n',
        '            log(f"   ⚠️ Submenu lỗi: {e}")\n',
        '\n',
        '        dismiss_popups(page)\n',
        '        page.screenshot(path="/tmp/debug_after_compose.png")\n',
        '        log("   📸 Screenshot sau click compose: /tmp/debug_after_compose.png")\n',
        '\n',
        '        # DEBUG: dump elements để xác nhận dialog upload đã mở\n',
        '        try:\n',
        '            els = page.evaluate("""\n',
        '                () => {\n',
        '                    return Array.from(document.querySelectorAll("button,input,[role=\'button\']"))\n',
        '                        .filter(e => e.offsetParent !== null)\n',
        '                        .map(e => ({\n',
        '                            tag: e.tagName,\n',
        '                            type: e.getAttribute("type") || "",\n',
        '                            aria: e.getAttribute("aria-label") || "",\n',
        '                            text: (e.innerText || "").trim().slice(0, 40),\n',
        '                            accept: e.getAttribute("accept") || ""\n',
        '                        })).slice(0, 30);\n',
        '                }\n',
        '            """)\n',
        '            log("   🔍 [DEBUG] Elements sau compose click:")\n',
        '            for el in els:\n',
        '                log(f\'      {el["tag"]} type="{el["type"]}" aria="{el["aria"]}" text="{el["text"]}" accept="{el["accept"]}"\')\n',
        '        except Exception as e:\n',
        '            log(f"   ⚠️ Không dump được: {e}")\n',
        '\n',
        '        # ── Bước 2: Upload ảnh ──\n',
        '        log("   📂 Upload ảnh...")\n',
        '        upload_done = False\n',
        '\n',
        '        # Đợi dialog upload xuất hiện (có text "Kéo ảnh" hoặc nút "Chọn từ máy tính")\n',
        '        for wait_i in range(6):\n',
        '            try:\n',
        '                upload_ready = page.evaluate("""\n',
        '                    () => {\n',
        '                        const txt = document.body.innerText || "";\n',
        '                        return txt.includes("Kéo ảnh") || txt.includes("Drag photos") || txt.includes("Chọn từ máy tính") || txt.includes("Select from computer") || !!document.querySelector(\'input[type="file"]\');\n',
        '                    }\n',
        '                """)\n',
        '                if upload_ready:\n',
        '                    log(f"   ✅ Dialog upload đã sẵn sàng")\n',
        '                    break\n',
        '                log(f"   ⏳ Chờ dialog upload... ({wait_i+1}/6)")\n',
        '                time.sleep(1.5)\n',
        '            except:\n',
        '                time.sleep(1.5)\n',
        '\n',
        '        # Cách 1: input[type=file] trực tiếp\n',
        '        try:\n',
        '            file_input = page.locator(\'input[type="file"]\').first\n',
        '            file_input.wait_for(state="attached", timeout=8000)\n',
        '            page.set_input_files(\'input[type="file"]\', local_image)\n',
        '            log("   ✅ Upload qua input[type=file]")\n',
        '            upload_done = True\n',
        '        except Exception as e:\n',
        '            log(f"   ⚠️ input[type=file] lỗi: {e}")\n',
        '\n',
        '        # Cách 2: expect_file_chooser khi click nút "Chọn từ máy tính"\n',
        '        if not upload_done:\n',
        '            btn_sels = [\n',
        '                \'button:has-text("Chọn từ máy tính")\',\n',
        '                \'button:has-text("Select from computer")\',\n',
        '                \'[role="button"]:has-text("Chọn từ máy tính")\',\n',
        '                \'[role="button"]:has-text("Select from computer")\',\n',
        '                \'button:has-text("Chọn")\',\n',
        '                \'button:has-text("Select")\',\n',
        '                \'[role="button"]:has-text("Chọn")\',\n',
        '                \'svg[aria-label="Phương tiện"]\',\n',
        '                \'svg[aria-label="Media"]\',\n',
        '            ]\n',
        '            for sel in btn_sels:\n',
        '                try:\n',
        '                    btn = page.locator(sel).first\n',
        '                    btn.wait_for(state="visible", timeout=5000)\n',
        '                    with page.expect_file_chooser(timeout=8000) as fc_info:\n',
        '                        btn.click()\n',
        '                    fc_info.value.set_files(local_image)\n',
        '                    log(f"   ✅ Upload qua file chooser: {sel}")\n',
        '                    upload_done = True\n',
        '                    break\n',
        '                except Exception as e:\n',
        '                    log(f"   ⚠️ file chooser {sel}: {e}")\n',
        '\n',
        '        # Cách 3: JS click input[type=file] ẩn\n',
        '        if not upload_done:\n',
        '            try:\n',
        '                with page.expect_file_chooser(timeout=8000) as fc_info:\n',
        '                    page.evaluate("() => { const i = document.querySelector(\'input[type=\\\"file\\\"]\'); if(i) i.click(); }")\n',
        '                fc_info.value.set_files(local_image)\n',
        '                log("   ✅ Upload qua JS click input file")\n',
        '                upload_done = True\n',
        '            except Exception as e:\n',
        '                log(f"   ⚠️ JS click file input lỗi: {e}")\n',
        '\n',
        '        if not upload_done:\n',
        '            page.screenshot(path="/tmp/debug_no_upload.png")\n',
        '            log("ERR:UPLOAD_FAILED")\n',
        '            sys.exit(6)\n',
        '\n',
        '        time.sleep(random.uniform(3.0, 5.0))\n',
        '        page.screenshot(path="/tmp/debug_after_upload.png")\n',
        '        log("   📸 Screenshot sau upload: /tmp/debug_after_upload.png")\n',
        '\n',
        '        # ── Bước 3: Bấm "Tiếp" trong dialog tạo bài (Cắt → Chỉnh sửa → Caption) ──\n',
        '        def click_tiep(page, step_name):\n',
        '            """Click nút Tiếp BÊN TRONG dialog tạo bài, không nhầm với nút ngoài feed"""\n',
        '            time.sleep(random.uniform(2.0, 3.0))\n',
        '            try:\n',
        '                # Tìm dialog tạo bài trước, rồi tìm nút Tiếp bên trong đó\n',
        '                clicked = page.evaluate("""\n',
        '                    () => {\n',
        '                        // Tìm dialog tạo bài — thường có header chứa "Cắt", "Chỉnh sửa", "Tạo bài viết mới", "Crop", "Edit", "Create new post"\n',
        '                        const dialogKeywords = ["cắt", "chỉnh sửa", "tạo bài viết", "crop", "edit", "create new post", "filters", "bộ lọc"];\n',
        '                        let dialog = null;\n',
        '                        // Tìm element chứa header của dialog tạo bài\n',
        '                        const allEls = Array.from(document.querySelectorAll(\'[role="dialog"], div[class*="modal"], div[class*="Modal"]\'));\n',
        '                        for (const el of allEls) {\n',
        '                            const txt = (el.innerText || "").toLowerCase();\n',
        '                            if (dialogKeywords.some(k => txt.includes(k))) {\n',
        '                                dialog = el;\n',
        '                                break;\n',
        '                            }\n',
        '                        }\n',
        '                        // Tìm nút Tiếp trong dialog\n',
        '                        const scope = dialog || document;\n',
        '                        const btns = Array.from(scope.querySelectorAll("button,[role=\'button\']"));\n',
        '                        const t = btns.find(b => {\n',
        '                            if (b.offsetParent === null || b.disabled) return false;\n',
        '                            const aria = (b.getAttribute("aria-label") || "").trim();\n',
        '                            const txt = (b.innerText || b.textContent || "").trim();\n',
        '                            return aria === "Tiếp" || aria === "Next" || txt === "Tiếp" || txt === "Next";\n',
        '                        });\n',
        '                        if (t) { t.click(); return (dialog ? "dialog:" : "page:") + (t.getAttribute("aria-label") || t.innerText || "ok"); }\n',
        '                        return null;\n',
        '                    }\n',
        '                """)\n',
        '                if clicked:\n',
        '                    log(f"   ✅ Click Tiếp ({step_name}): {clicked}")\n',
        '                    return True\n',
        '            except Exception as e:\n',
        '                log(f"   ⚠️ JS Tiếp lỗi ({step_name}): {e}")\n',
        '            # Playwright fallback — ưu tiên last visible (nút trong dialog thường ở trên cùng)\n',
        '            for sel in [\'[aria-label="Tiếp"]\', \'[aria-label="Next"]\', \'button:has-text("Tiếp")\', \'button:has-text("Next")\']:\n',
        '                try:\n',
        '                    btn = page.locator(sel).first\n',
        '                    btn.wait_for(state="visible", timeout=4000)\n',
        '                    btn.click()\n',
        '                    log(f"   ✅ Click Tiếp ({step_name}) PW: {sel}")\n',
        '                    return True\n',
        '                except:\n',
        '                    pass\n',
        '            log(f"   ⚠️ Không tìm được Tiếp ({step_name})")\n',
        '            return False\n',
        '\n',
        '        # ── Bước 3a: Mở panel crop và chọn "Gốc" ──\n',
        '        time.sleep(random.uniform(1.5, 2.5))\n',
        '        try:\n',
        '            # Bước 1: Click icon mở panel crop (icon hình vuông góc dưới trái của dialog)\n',
        '            # Trong debug_after_upload.png thấy icon expand ở bottom-left của ảnh\n',
        '            opened_panel = False\n',
        '            crop_icon_sels = [\n',
        '                \'[aria-label="Chọn tỷ lệ cắt"]\',\n',
        '                \'[aria-label="Select crop"]\',\n',
        '                \'[aria-label="Chọn kích thước cắt"]\',\n',
        '                \'[aria-label="Crop"]\',\n',
        '                \'button[aria-label*="cắt" i]\',\n',
        '                \'button[aria-label*="crop" i]\',\n',
        '                \'button[aria-label*="kích thước" i]\',\n',
        '            ]\n',
        '            for crop_sel in crop_icon_sels:\n',
        '                try:\n',
        '                    btn = page.locator(crop_sel).first\n',
        '                    btn.wait_for(state="visible", timeout=3000)\n',
        '                    btn.click()\n',
        '                    time.sleep(1.0)\n',
        '                    log(f"   🖱️ Mở panel crop qua: {crop_sel}")\n',
        '                    opened_panel = True\n',
        '                    break\n',
        '                except:\n',
        '                    pass\n',
        '            # Fallback: tìm qua JS — button có text "Chọn kích thước cắt" hoặc icon expand\n',
        '            if not opened_panel:\n',
        '                try:\n',
        '                    js_result = page.evaluate("""\n',
        '                        () => {\n',
        '                            const btns = Array.from(document.querySelectorAll("button,[role=\'button\']"));\n',
        '                            const t = btns.find(b => {\n',
        '                                if (b.offsetParent === null) return false;\n',
        '                                const aria = (b.getAttribute("aria-label") || "").toLowerCase();\n',
        '                                const txt = (b.innerText || b.textContent || "").toLowerCase();\n',
        '                                return aria.includes("cắt") || aria.includes("crop") || aria.includes("kích thước") || txt.includes("kích thước");\n',
        '                            });\n',
        '                            if (t) { t.click(); return t.getAttribute("aria-label") || t.innerText || "clicked"; }\n',
        '                            return null;\n',
        '                        }\n',
        '                    """)\n',
        '                    if js_result:\n',
        '                        log(f"   🖱️ Mở crop panel JS: {js_result}")\n',
        '                        opened_panel = True\n',
        '                        time.sleep(1.0)\n',
        '                except Exception as e:\n',
        '                    log(f"   ⚠️ JS open crop panel lỗi: {e}")\n',
        '\n',
        '            # Bước 2: Chọn "Gốc" trong panel crop\n',
        '            try:\n',
        '                selected_ratio = page.evaluate("""\n',
        '                    () => {\n',
        '                        const btns = Array.from(document.querySelectorAll("button,[role=\'button\'],span,div"));\n',
        '                        const t = btns.find(b => {\n',
        '                            if (b.offsetParent === null) return false;\n',
        '                            const txt = (b.innerText || b.textContent || "").trim();\n',
        '                            const aria = (b.getAttribute("aria-label") || "").trim();\n',
        '                            return txt === "Gốc" || txt === "Original" || aria === "Gốc" || aria === "Original";\n',
        '                        });\n',
        '                        if (t) { t.click(); return t.innerText || t.getAttribute("aria-label") || "clicked"; }\n',
        '                        return null;\n',
        '                    }\n',
        '                """)\n',
        '                if selected_ratio:\n',
        '                    log(f"   ✅ Đã chọn tỷ lệ Gốc: {selected_ratio}")\n',
        '                    time.sleep(0.8)\n',
        '                    # Click lại icon crop để đóng panel\n',
        '                    try:\n',
        '                        for crop_sel in crop_icon_sels:\n',
        '                            try:\n',
        '                                page.locator(crop_sel).first.click(timeout=1500)\n',
        '                                break\n',
        '                            except: pass\n',
        '                    except: pass\n',
        '                else:\n',
        '                    log("   ⚠️ Không tìm thấy nút Gốc trong panel")\n',
        '            except Exception as e:\n',
        '                log(f"   ⚠️ Chọn Gốc lỗi: {e}")\n',
        '        except Exception as e:\n',
        '            log(f"   ⚠️ Crop panel lỗi: {e}")\n',
        '\n',
        '        time.sleep(random.uniform(1.0, 1.5))\n',
        '        page.screenshot(path="/tmp/debug_crop_selected.png")\n',
        '        log("   📸 Sau chọn tỷ lệ: /tmp/debug_crop_selected.png")\n',
        '\n',
        '        # Bước Cắt → Chỉnh sửa\n',
        '        click_tiep(page, "Cắt→Chỉnh sửa")\n',
        '        time.sleep(random.uniform(2.0, 3.0))\n',
        '        page.screenshot(path="/tmp/debug_step_chinh_sua.png")\n',
        '        # Log tiêu đề dialog hiện tại\n',
        '        try:\n',
        '            header_txt = page.evaluate("() => { const h = document.querySelector(\'[role=\\\"dialog\\\"] h1, [role=\\\"dialog\\\"] header\'); return h ? h.innerText : \'?\'; }")\n',
        '            log(f"   📍 Dialog header sau Tiếp 1: {header_txt}")\n',
        '        except: pass\n',
        '\n',
        '        # Bước Chỉnh sửa → Caption\n',
        '        click_tiep(page, "Chỉnh sửa→Caption")\n',
        '        time.sleep(random.uniform(2.5, 3.5))\n',
        '        page.screenshot(path="/tmp/debug_caption_step.png")\n',
        '        # Log tiêu đề dialog hiện tại\n',
        '        try:\n',
        '            header_txt = page.evaluate("() => { const h = document.querySelector(\'[role=\\\"dialog\\\"] h1, [role=\\\"dialog\\\"] header\'); return h ? h.innerText : \'?\'; }")\n',
        '            log(f"   📍 Dialog header sau Tiếp 2: {header_txt}")\n',
        '        except: pass\n',
        '\n',
        '        # ── Bước 4: Nhập caption — đợi màn "Tạo bài viết mới" xuất hiện ──\n',
        '        # Đợi dialog chuyển sang màn caption (header = "Tạo bài viết mới")\n',
        '        for wait_i in range(8):\n',
        '            try:\n',
        '                header = page.evaluate("""\n',
        '                    () => {\n',
        '                        const els = Array.from(document.querySelectorAll("h1,header,[role=\'heading\']"));\n',
        '                        return els.map(e => (e.innerText || "").trim()).find(t => t.length > 0) || "";\n',
        '                    }\n',
        '                """)\n',
        '                if header and ("tạo bài viết" in header.lower() or "create new post" in header.lower() or "new post" in header.lower()):\n',
        '                    log(f"   ✅ Đã đến màn Caption: {header}")\n',
        '                    break\n',
        '                log(f"   ⏳ Chờ màn Caption... header={header} ({wait_i+1}/8)")\n',
        '                time.sleep(1.5)\n',
        '            except:\n',
        '                time.sleep(1.5)\n',
        '\n',
        '        caption_typed = False\n',
        '        log(f"   📝 Bắt đầu nhập caption ({len(caption)} ký tự)...")\n',
        '        caption_sels = [\n',
        '            \'[aria-label="Viết chú thích..."]\',\n',
        '            \'[aria-label="Write a caption..."]\',\n',
        '            \'[placeholder="Viết chú thích..."]\',\n',
        '            \'[placeholder="Write a caption..."]\',\n',
        '            \'div[role="textbox"][contenteditable="true"]\',\n',
        '            \'[contenteditable="true"]\',\n',
        '            \'div[role="textbox"]\',\n',
        '        ]\n',
        '\n',
        '        def try_set_caption(page, sel, caption_text):\n',
        '            """Thử set caption vào element, trả về số ký tự đã set hoặc 0"""\n',
        '            result = page.evaluate("""\n',
        '                ([sel, captionText]) => {\n',
        '                    const el = document.querySelector(sel);\n',
        '                    if (!el) return {ok: false, method: "no_el", len: 0};\n',
        '                    el.focus();\n',
        '\n',
        '                    // === Phương pháp 1: React fiber setState ===\n',
        '                    try {\n',
        '                        const fiberKey = Object.keys(el).find(k => k.startsWith("__reactFiber") || k.startsWith("__reactInternalInstance"));\n',
        '                        if (fiberKey) {\n',
        '                            let fiber = el[fiberKey];\n',
        '                            for (let i = 0; i < 20 && fiber; i++) {\n',
        '                                const inst = fiber.stateNode;\n',
        '                                if (inst && inst.setState) {\n',
        '                                    inst.setState({value: captionText});\n',
        '                                    el.dispatchEvent(new Event("input", {bubbles: true}));\n',
        '                                    return {ok: true, method: "react_setState", len: captionText.length};\n',
        '                                }\n',
        '                                fiber = fiber.return;\n',
        '                            }\n',
        '                        }\n',
        '                    } catch(e) {}\n',
        '\n',
        '                    // === Phương pháp 2: React props onChange ===\n',
        '                    try {\n',
        '                        const propsKey = Object.keys(el).find(k => k.startsWith("__reactProps"));\n',
        '                        if (propsKey && el[propsKey] && el[propsKey].onChange) {\n',
        '                            el.textContent = captionText;\n',
        '                            const event = new InputEvent("input", {bubbles: true, cancelable: true, data: captionText, inputType: "insertText"});\n',
        '                            Object.defineProperty(event, "target", {value: el});\n',
        '                            el[propsKey].onChange(event);\n',
        '                            return {ok: true, method: "react_props_onChange", len: (el.innerText||el.textContent||"").trim().length};\n',
        '                        }\n',
        '                    } catch(e) {}\n',
        '\n',
        '                    // === Phương pháp 3: Clipboard paste via DataTransfer (Lexical editor) ===\n',
        '                    // Instagram dùng Lexical editor — cần dispatch "paste" event với DataTransfer\n',
        '                    try {\n',
        '                        // Xóa nội dung cũ trước\n',
        '                        document.execCommand("selectAll", false, null);\n',
        '                        document.execCommand("delete", false, null);\n',
        '                        // Tạo ClipboardEvent với DataTransfer chứa text\n',
        '                        const dt = new DataTransfer();\n',
        '                        dt.setData("text/plain", captionText);\n',
        '                        const pasteEvent = new ClipboardEvent("paste", {\n',
        '                            bubbles: true,\n',
        '                            cancelable: true,\n',
        '                            clipboardData: dt\n',
        '                        });\n',
        '                        el.dispatchEvent(pasteEvent);\n',
        '                        const val3 = (el.innerText || el.textContent || "").trim();\n',
        '                        if (val3.length > 3) return {ok: true, method: "clipboard_paste_event", len: val3.length};\n',
        '                    } catch(e) {}\n',
        '\n',
        '                    // === Phương pháp 4: execCommand + force InputEvent với nativeEvent ===\n',
        '                    try {\n',
        '                        document.execCommand("selectAll", false, null);\n',
        '                        document.execCommand("delete", false, null);\n',
        '                        const chunks = captionText.match(/[\\s\\S]{1,50}/g) || [captionText];\n',
        '                        for (const chunk of chunks) {\n',
        '                            document.execCommand("insertText", false, chunk);\n',
        '                        }\n',
        '                        // Dispatch input event AFTER để Lexical flush state\n',
        '                        el.dispatchEvent(new InputEvent("input", {bubbles: true, cancelable: false, inputType: "insertText", data: captionText}));\n',
        '                        el.dispatchEvent(new Event("change", {bubbles: true}));\n',
        '                        const val4 = (el.innerText || el.value || el.textContent || "").trim();\n',
        '                        return {ok: val4.length > 3, method: "execCommand_plus_events", len: val4.length};\n',
        '                    } catch(e) {}\n',
        '\n',
        '                    return {ok: false, method: "all_failed", len: 0};\n',
        '                }\n',
        '            """, [sel, caption_text])\n',
        '            return result\n',
        '\n',
        '        def _verify_caption(page, sel):\n',
        '            try:\n',
        '                return page.evaluate(f"""\n',
        '                    () => {{\n',
        '                        const el = document.querySelector(\'{sel}\');\n',
        '                        if (!el) return "";\n',
        '                        return (el.innerText || el.value || el.textContent || "").trim();\n',
        '                    }}\n',
        '                """)\n',
        '            except:\n',
        '                return ""\n',
        '\n',
        '        for sel in caption_sels:\n',
        '            try:\n',
        '                el = page.locator(sel).first\n',
        '                el.wait_for(state="visible", timeout=8000)\n',
        '                log(f"   🔍 Thử caption selector: {sel}")\n',
        '                el.scroll_into_view_if_needed()\n',
        '                el.click()\n',
        '                time.sleep(0.5)\n',
        '\n',
        '                # ── Ưu tiên 1: CDP clipboard → Ctrl+V (đáng tin cậy nhất với Lexical) ──\n',
        '                cdp_ok = False\n',
        '                try:\n',
        '                    import json as _json\n',
        '                    cdp = context.new_cdp_session(page)\n',
        '                    cdp.send("Browser.grantPermissions", {\n',
        '                        "permissions": ["clipboardReadWrite", "clipboardSanitizedWrite"]\n',
        '                    })\n',
        '                    page.evaluate(f"""\n',
        '                        async () => {{\n',
        '                            await navigator.clipboard.writeText({_json.dumps(caption)});\n',
        '                        }}\n',
        '                    """)\n',
        '                    time.sleep(0.3)\n',
        '                    el.click()\n',
        '                    page.keyboard.press("Control+a")\n',
        '                    time.sleep(0.1)\n',
        '                    page.keyboard.press("Control+v")\n',
        '                    time.sleep(1.5)\n',
        '                    val = _verify_caption(page, sel)\n',
        '                    log(f"   📌 CDP clipboard paste: [{(val or \'\')[:80]}...]")\n',
        '                    if val and len(val.strip()) > 3:\n',
        '                        log(f"   ✅ Caption OK via CDP clipboard ({len(val)} ký tự)")\n',
        '                        caption_typed = True\n',
        '                        cdp_ok = True\n',
        '                        break\n',
        '                    else:\n',
        '                        log("   ⚠️ CDP clipboard không thấy text trong editor, thử keyboard.type...")\n',
        '                except Exception as cdp_e:\n',
        '                    log(f"   ⚠️ CDP clipboard lỗi: {cdp_e}, thử keyboard.type...")\n',
        '\n',
        '                if cdp_ok:\n',
        '                    break\n',
        '\n',
        '                # ── Ưu tiên 2: page.keyboard.type() từng chunk ──\n',
        '                # Lexical LUÔN nhận keyboard events thật — đây là fallback chắc chắn nhất\n',
        '                kbt_ok = False\n',
        '                try:\n',
        '                    el.click()\n',
        '                    time.sleep(0.3)\n',
        '                    # Xóa nội dung cũ\n',
        '                    page.keyboard.press("Control+a")\n',
        '                    time.sleep(0.1)\n',
        '                    page.keyboard.press("Delete")\n',
        '                    time.sleep(0.2)\n',
        '                    # Gõ theo chunk 80 ký tự để không bị drop\n',
        '                    chunk_size = 80\n',
        '                    chunks = [caption[i:i+chunk_size] for i in range(0, len(caption), chunk_size)]\n',
        '                    log(f"   ⌨️ keyboard.type {len(chunks)} chunks x {chunk_size} ký tự...")\n',
        '                    for ci, chunk in enumerate(chunks):\n',
        '                        page.keyboard.type(chunk, delay=15)\n',
        '                        time.sleep(0.15)\n',
        '                    time.sleep(1.0)\n',
        '                    val = _verify_caption(page, sel)\n',
        '                    log(f"   📌 keyboard.type result: [{(val or \'\')[:80]}...]")\n',
        '                    if val and len(val.strip()) > 3:\n',
        '                        log(f"   ✅ Caption OK via keyboard.type ({len(val)} ký tự)")\n',
        '                        caption_typed = True\n',
        '                        kbt_ok = True\n',
        '                        break\n',
        '                    else:\n',
        '                        log("   ⚠️ keyboard.type không thấy text, thử JS method...")\n',
        '                except Exception as ke:\n',
        '                    log(f"   ⚠️ keyboard.type lỗi: {ke}")\n',
        '\n',
        '                if kbt_ok:\n',
        '                    break\n',
        '\n',
        '                # ── Ưu tiên 3: JS DataTransfer paste event (last resort) ──\n',
        '                try:\n',
        '                    el.click()\n',
        '                    time.sleep(0.3)\n',
        '                    import json as _j2\n',
        '                    js_result = page.evaluate(f"""\n',
        '                        ([captionText]) => {{\n',
        '                            const el = document.querySelector(\'{sel}\');\n',
        '                            if (!el) return 0;\n',
        '                            el.focus();\n',
        '                            // Xóa cũ\n',
        '                            document.execCommand("selectAll", false, null);\n',
        '                            document.execCommand("delete", false, null);\n',
        '                            // Dispatch paste event với DataTransfer — Lexical xử lý\n',
        '                            const dt = new DataTransfer();\n',
        '                            dt.setData("text/plain", captionText);\n',
        '                            el.dispatchEvent(new ClipboardEvent("paste", {{\n',
        '                                bubbles: true, cancelable: true, clipboardData: dt\n',
        '                            }}));\n',
        '                            return (el.innerText || el.textContent || "").trim().length;\n',
        '                        }}\n',
        '                    """, [caption])\n',
        '                    time.sleep(0.8)\n',
        '                    val = _verify_caption(page, sel)\n',
        '                    log(f"   📌 JS paste event result: len={js_result}, DOM=[{(val or \'\')[:80]}...]")\n',
        '                    if val and len(val.strip()) > 3:\n',
        '                        log(f"   ✅ Caption OK via JS paste event ({len(val)} ký tự)")\n',
        '                        caption_typed = True\n',
        '                        break\n',
        '                except Exception as je:\n',
        '                    log(f"   ⚠️ JS paste event lỗi: {je}")\n',
        '\n',
        '            except Exception as e:\n',
        '                log(f"   ⚠️ Caption sel [{sel}]: {e}")\n',
        '\n',
        '        if not caption_typed:\n',
        '            log("   ⚠️ Không nhập được caption — bài sẽ đăng không có caption")\n',
        '\n',
        '        # Đợi Lexical flush internal state, rồi click blur để trigger onChange\n',
        '        time.sleep(random.uniform(2.0, 3.0))\n',
        '        try:\n',
        '            page.keyboard.press("Escape")  # blur editor\n',
        '            time.sleep(0.3)\n',
        '        except: pass\n',
        '        time.sleep(1.5)\n',
        '        page.screenshot(path="/tmp/debug_before_share.png")\n',
        '\n',
        '        # DEBUG buttons\n',
        '        try:\n',
        '            btn_info = page.evaluate("""\n',
        '                () => Array.from(document.querySelectorAll("button,[role=\'button\']")).map(b => ({\n',
        '                    text: (b.innerText || b.textContent || "").trim().slice(0, 40),\n',
        '                    aria: b.getAttribute("aria-label") || "",\n',
        '                    visible: b.offsetParent !== null,\n',
        '                    disabled: b.disabled\n',
        '                })).filter(b => b.visible)\n',
        '            """)\n',
        '            log("   🔍 [DEBUG] Buttons trước Share:")\n',
        '            for bi in btn_info:\n',
        '                log(f\'      text="{bi["text"]}" aria="{bi["aria"]}" disabled={bi["disabled"]}\')\n',
        '        except Exception as e:\n',
        '            log(f"   ⚠️ Không dump buttons: {e}")\n',
        '\n',
        '        # ── Bước 5: Click "Chia sẻ" — retry tối đa 3 lần, chờ nút enabled ──\n',
        '        posted = False\n',
        '        for share_attempt in range(3):\n',
        '            if share_attempt > 0:\n',
        '                log(f"   🔄 Retry Share lần {share_attempt+1}...")\n',
        '                time.sleep(3)\n',
        '            # JS click — tìm nút Chia sẻ/Share TRONG DIALOG tạo bài (header chứa "Tạo bài viết mới")\n',
        '            try:\n',
        '                clicked = page.evaluate("""\n',
        '                    () => {\n',
        '                        // Tìm dialog tạo bài mới — header phải chứa "Tạo bài viết mới" hoặc "Create new post"\n',
        '                        const postDialogKeywords = ["tạo bài viết mới", "create new post"];\n',
        '                        let dialog = null;\n',
        '                        const allEls = Array.from(document.querySelectorAll(\'[role="dialog"], div[class*="modal"], div[class*="Modal"]\'));\n',
        '                        for (const el of allEls) {\n',
        '                            const txt = (el.innerText || "").toLowerCase();\n',
        '                            if (postDialogKeywords.some(k => txt.includes(k))) {\n',
        '                                dialog = el;\n',
        '                                break;\n',
        '                            }\n',
        '                        }\n',
        '                        // Nếu không tìm thấy dialog cụ thể, tìm nút Chia sẻ nào có aria-label (nút trong dialog thường có aria-label rõ ràng)\n',
        '                        const scope = dialog || document;\n',
        '                        const btns = Array.from(scope.querySelectorAll("button,[role=\'button\']"));\n',
        '                        // Ưu tiên nút có aria-label chính xác và không disabled\n',
        '                        let t = btns.find(b => {\n',
        '                            if (b.offsetParent === null || b.disabled) return false;\n',
        '                            const aria = (b.getAttribute("aria-label") || "").trim();\n',
        '                            return aria === "Chia sẻ" || aria === "Share";\n',
        '                        });\n',
        '                        // Nếu không có aria, tìm qua text nhưng chỉ trong dialog\n',
        '                        if (!t && dialog) {\n',
        '                            t = btns.find(b => {\n',
        '                                if (b.offsetParent === null || b.disabled) return false;\n',
        '                                const txt = (b.innerText || b.textContent || "").trim();\n',
        '                                return txt === "Chia sẻ" || txt === "Share";\n',
        '                            });\n',
        '                        }\n',
        '                        if (t) {\n',
        '                            t.click();\n',
        '                            return (dialog ? "dialog:" : "page:") + (t.getAttribute("aria-label") || t.innerText || "clicked");\n',
        '                        }\n',
        '                        return null;\n',
        '                    }\n',
        '                """)\n',
        '                if clicked:\n',
        '                    posted = True\n',
        '                    log(f"   🚀 Click Chia sẻ JS: {clicked}")\n',
        '                    break\n',
        '            except Exception as e:\n',
        '                log(f"   ⚠️ JS Share lỗi: {e}")\n',
        '            # Playwright fallback — dùng locator trong dialog\n',
        '            for sel in [\'[aria-label="Chia sẻ"]\', \'[aria-label="Share"]\']:\n',
        '                try:\n',
        '                    # Chỉ tìm trong dialog tạo bài\n',
        '                    dialog_loc = page.locator(\'[role="dialog"]:has-text("Tạo bài viết mới"), [role="dialog"]:has-text("Create new post")\')\n',
        '                    btn = dialog_loc.locator(sel).first\n',
        '                    btn.wait_for(state="visible", timeout=5000)\n',
        '                    for _ in range(10):\n',
        '                        if not btn.is_disabled():\n',
        '                            break\n',
        '                        time.sleep(0.5)\n',
        '                    btn.click(force=True)\n',
        '                    posted = True\n',
        '                    log(f"   🚀 Click Chia sẻ PW (dialog): {sel}")\n',
        '                    break\n',
        '                except Exception as e:\n',
        '                    log(f"      {sel}: lỗi {e}")\n',
        '            if posted:\n',
        '                break\n',
        '\n',
        '        if not posted:\n',
        '            page.screenshot(path="/tmp/debug_no_share_btn.png")\n',
        '            log("ERR:NO_SHARE_BTN")\n',
        '            sys.exit(4)\n',
        '\n',
        '        # ── Chờ xác nhận ──\n',
        '        log("   ⏳ Chờ xác nhận bài đã đăng...")\n',
        '        time.sleep(10)\n',
        '        page.screenshot(path="/tmp/debug_after_post.png")\n',
        '        log(f"   📸 Screenshot sau đăng: /tmp/debug_after_post.png")\n',
        '        log(f"   🔗 URL sau đăng: {page.url}")\n',
        '\n',
        '        # Kiểm tra lỗi UI\n',
        '        for err_sel in [\n',
        '            \'[role="alert"]\',\n',
        '            \'div:has-text("Something went wrong")\',\n',
        '            \'div:has-text("Đã xảy ra lỗi")\',\n',
        '        ]:\n',
        '            try:\n',
        '                el = page.locator(err_sel).first\n',
        '                if el.is_visible():\n',
        '                    log(f"   ❌ Phát hiện lỗi: {err_sel}")\n',
        '                    log("ERR:POST_FAILED_UI_ERROR")\n',
        '                    sys.exit(7)\n',
        '            except:\n',
        '                pass\n',
        '\n',
        '        context.storage_state(path=SESSION_FILE)\n',
        '        post_id = "ig_" + str(int(time.time()))\n',
        '        if "/p/" in page.url or "instagram.com/@" in page.url:\n',
        '            post_id = page.url\n',
        '            log(f"   ✅ Xác nhận URL bài đăng: {post_id}")\n',
        '        else:\n',
        '            log(f"   ⚠️ URL sau đăng: {page.url}")\n',
        '        log(f"OK:{post_id}")\n',
        '        browser.close()\n',
        '\n',
        '    except Exception as e:\n',
        '        import traceback\n',
        '        traceback.print_exc()\n',
        '        try: page.screenshot(path="/tmp/err_exception.png")\n',
        '        except: pass\n',
        '        log(f"ERR:EXCEPTION:{str(e)[:150]}")\n',
        '        browser.close()\n',
        '        sys.exit(5)\n',
    ]
    with open(path, 'w', encoding='utf-8') as f:
        f.writelines(lines)
    return path

def post_to_instagram_browser(content, image_url='', hashtags=''):
    if not image_url:
        print('❌ Thiếu image_url! Instagram cần ảnh để đăng.')
        return None

    pw_worker = _write_pw_worker()
    env = os.environ.copy()
    env['PW_PAYLOAD'] = json.dumps({
        'content':      content,
        'image_url':    image_url,
        'hashtags':     hashtags,
        'session_file': SESSION_FILE,
        'instagram_url': INSTAGRAM_URL,
    })

    result = subprocess.run(
        [sys.executable, pw_worker],
        capture_output=True, text=True, encoding='utf-8',
        timeout=180, env=env
    )

    for line in result.stdout.splitlines():
        if line.startswith('OK:'):
            print(f'   ✅ Đăng thành công: {line[3:]}')
            return line[3:]
        else:
            print(line)

    if result.stderr:
        print('--- stderr ---')
        print(result.stderr[-1000:])
    return None

def process_and_post(sheet, post_data):
    row       = post_data['row']
    content   = post_data['content']
    image_url = post_data['image_url']
    hashtags  = post_data['hashtags']

    print(f'\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━')
    print(f'📌 Xử lý bài post (row {row}):')
    print(f'   Nội dung: {content[:80]}...' if len(content) > 80 else f'   Nội dung: {content}')
    print(f'   Ảnh: {image_url[:60]}...' if len(image_url) > 60 else f'   Ảnh: {image_url}')

    post_id = post_to_instagram_browser(content, image_url, hashtags)

    if post_id:
        update_status(sheet, row, 'done', str(post_id))
        print('✅ Đăng bài thành công!')
    else:
        update_status(sheet, row, 'error')
        print('❌ Đăng bài thất bại!')
        sys.exit(1)

    wait_sec = random.randint(30, 60)
    print(f'   ⏳ Chờ {wait_sec}s trước bài kế tiếp...')
    time.sleep(wait_sec)

if __name__ == '__main__':
    print('\n🤖 Instagram AutoPost Bot (GitHub Actions mode) đang khởi động...')
    restore_secrets()

    try:
        sheet = connect_sheet()
        posts = get_pending_posts(sheet)
        if not posts:
            print('📭 Không có bài nào cần đăng lúc này.')
            sys.exit(0)
        print(f'📋 Tìm thấy {len(posts)} bài cần đăng')
        for post in posts:
            process_and_post(sheet, post)
    except Exception as e:
        import traceback
        traceback.print_exc()
        print(f'❌ Lỗi: {e}')
        sys.exit(1)

    print(f'\n✅ Hoàn thành lúc {datetime.now().strftime("%d/%m/%Y %H:%M:%S")}')